import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const ROOT_DIR = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const FIXTURES_DIR = path.join(ROOT_DIR, 'src', 'fixtures');
const SEEDS_DIR = path.join(ROOT_DIR, 'src', 'app', 'seeds');

/**
 * Generate all seed modules from the fixture package folders.
 */
function main() {
  const seedSpecs = discoverSeedSpecs();
  cleanGeneratedSeedModules();

  for (const spec of seedSpecs) {
    writeSeedModule(spec);
  }

  writeSeedIndexModule(seedSpecs);
}

/**
 * Discover all fixture package folders that should produce generated seed modules.
 */
function discoverSeedSpecs() {
  return fs.readdirSync(FIXTURES_DIR)
    .map((entryName) => path.join(FIXTURES_DIR, entryName))
    .filter((entryPath) => fs.statSync(entryPath).isDirectory())
    .map((fixtureRoot) => {
      const fixtureName = path.basename(fixtureRoot);
      const fixtureDir = path.join(fixtureRoot, fixtureName);
      const pluginJsonPath = path.join(fixtureDir, 'plugin.json');

      if (!fs.existsSync(pluginJsonPath)) {
        return null;
      }

      return {
        fixtureName,
        fixtureDir,
        outputFile: path.join(SEEDS_DIR, `${fixtureName}.ts`),
        exportName: `${toConstantCase(fixtureName)}_SEED_FILES`,
      };
    })
    .filter(Boolean)
    .sort((left, right) => left.fixtureName.localeCompare(right.fixtureName));
}

/**
 * Remove previously generated seed modules before regeneration.
 */
function cleanGeneratedSeedModules() {
  fs.mkdirSync(SEEDS_DIR, { recursive: true });

  for (const entryName of fs.readdirSync(SEEDS_DIR)) {
    if (!entryName.endsWith('.ts')) {
      continue;
    }

    fs.rmSync(path.join(SEEDS_DIR, entryName), { force: true });
  }
}

/**
 * Write one generated seed module from a fixture directory.
 */
function writeSeedModule(spec) {
  const files = collectFiles(spec.fixtureDir);
  const entries = Object.fromEntries(files.map((filePath) => {
    const relativePath = toPosixPath(path.relative(spec.fixtureDir, filePath));
    const content = fs.readFileSync(filePath, 'utf8');
    return [relativePath, content];
  }));

  fs.mkdirSync(path.dirname(spec.outputFile), { recursive: true });
  fs.writeFileSync(spec.outputFile, renderSeedModule(spec.exportName, entries), 'utf8');
}

/**
 * Collect all files beneath one directory in stable path order.
 */
function collectFiles(directory) {
  const discovered = [];

  walkDirectory(directory, discovered);
  return discovered.sort((left, right) => left.localeCompare(right));
}

/**
 * Walk one fixture directory recursively and accumulate file paths.
 */
function walkDirectory(directory, discovered) {
  for (const entryName of fs.readdirSync(directory)) {
    const entryPath = path.join(directory, entryName);
    const stats = fs.statSync(entryPath);

    if (stats.isDirectory()) {
      walkDirectory(entryPath, discovered);
      continue;
    }

    discovered.push(entryPath);
  }
}

/**
 * Render one generated TypeScript seed module.
 */
function renderSeedModule(exportName, entries) {
  const serializedEntries = Object.entries(entries)
    .map(([relativePath, content]) => `  ${JSON.stringify(relativePath)}: ${JSON.stringify(content)},`)
    .join('\n');

  return [
    '// This file is generated by scripts/generate-seeds.mjs. Do not edit manually.',
    `export const ${exportName}: Record<string, string> = {`,
    serializedEntries,
    '};',
    '',
  ].join('\n');
}

/**
 * Write the generated barrel file for all discovered seed modules.
 */
function writeSeedIndexModule(seedSpecs) {
  const lines = ['// This file is generated by scripts/generate-seeds.mjs. Do not edit manually.'];

  for (const spec of seedSpecs) {
    lines.push(`export { ${spec.exportName} } from './${spec.fixtureName}';`);
  }

  lines.push('');
  fs.writeFileSync(path.join(SEEDS_DIR, 'index.ts'), lines.join('\n'), 'utf8');
}

/**
 * Normalize a path to forward-slash separators for seed keys.
 */
function toPosixPath(targetPath) {
  return targetPath.replace(/\\/gu, '/');
}

/**
 * Convert a kebab-case fixture name into an upper snake-case export name prefix.
 */
function toConstantCase(value) {
  return value.replace(/[^a-zA-Z0-9]+/gu, '_').replace(/^_+|_+$/gu, '').toUpperCase();
}

main();